add ~timluc's gall guide
urbit/urbit.org pull request #1077
Opened 2021-08-25 17:03 UTC by drbeefsupreme

Long overdue, this PR adds @timlucmiptev 's Gall Guide. I've made a lot of
edits, but they're all minor. Mostly style adjustments and typos. I've also revised the
structure a bit to better fit with the documentation:
 - The data types page is in the main Gall folder
 - The generators appendix has been added `using/os/shell.md`
 - The troubleshooting page is in the main Gall folder

This PR is marked as a draft because there are still a few outstanding issues.

 - In ford.md, running `:fordexample %mark-example` prints out the HTML as
   a raw noun. I'm guessing this is an issue with the HTML mark itself, or the
   pretty printer. So outside of the scope of this PR, but maybe there's a way
   to change `%mark-example` so that it prints appropriately?
 - Several parts of it are out of date. For instance, it refers to
   `chat-store.hoon`, which has been deprecated by graph-store. This might be
   fine from a pedagogical perspective, though. I don't think this needs to be
   revised before the PR is merged, but it should be added as an issue in the
   repo.
 - Links to the marks documentation in several places added in #769 would be
   good, but it hasn't been merged yet.
 - The exercise in `scry.md` wants you to write a poke to subscribe to updates
   from `chat-store`. This is no longer possible.
 - All the example code still refers to @timlucmiptev 's repository. This should
   refer to an official `urbit` repo. I've asked @jahlehman to make an examples
   repo. The only issue this immediately creates, though, is that one of the
   marks is missing the `+grad` arm, which is unacceptable for a tutorial where
   the user probably won't know why they have that issue. So to me this is an
   actual blocker to merge it.
   
 Overall, its still an improvement so it may be fine to merge as-is (except for
 the example code issue noted last), as long as
 the out of date parts are noted as such.

2021-09-16 12:31 UTC, tinnus-napbus requested changes
looks fine afaics, just a couple of list layout errors. I think the guide itself needs substantial changes to its structure, style, flow and so forth but we should get it up first and then can look at how to improve it

2021-09-16 12:31 UTC, tinnus-napbus commented on content/docs/userspace/gall/data-types.md
> +  - usually in the form `(quip card _this)` or `(quip card _state_)`, where
```suggestion
  - usually in the form `(quip card _this)` or `(quip card _state)`, where
```

2021-09-16 12:31 UTC, tinnus-napbus commented on content/docs/userspace/gall/data-types.md
> +```
```suggestion
  - A `[type noun]`. This "marks" the data as a type so that we can extract it
    into that type from the `vase`.
  - Use this when you don't know at creation time what type of data will be
    coming into a function. Having vase as the type of a Gall arm forces
    messages sent to that arm to mark their type.
  - ```
    ::  Example, q is ~timluc-miptev in atom form
    ~zod:dojo> !>(~timluc-miptev)
    [#t/@p q=3.690.144]
    ```
```

2021-09-16 12:31 UTC, tinnus-napbus commented on content/docs/userspace/gall/data-types.md
> +`note:agent:gall` and `gift:agent:gall` consist of.
```suggestion
* `wind` (`sys/arvo.hoon`)
  - Gall `card`s are of type `(wind note gift)`
  - ```
    ::  wind is a tagged union of:
    [%pass p=path q=a] [%slip p=a] [%give p=b]
    ```
  - What this means in practice is that to make a Gall card, you make it as one of:
    * `[%pass p=path q=note:agent:gall]`
    * `[%give p=gift:agent:gall]`
  - In the "Gall Types" section below, we'll see what `note:agent:gall` and `gift:agent:gall` consist of.
```

2021-09-16 12:31 UTC, tinnus-napbus commented on content/docs/userspace/gall/data-types.md
> +returns from vanes. To find their full source, just search for `++ note-arvo` or
```suggestion
responses from vanes. To find their full source, just search for `++ note-arvo` or
```

2021-09-16 13:44 UTC, tinnus-napbus commented
I have submitted https://github.com/timlucmiptev/gall-guide/pull/27 to add the missing +grad arms, @timlucmiptev please merge

2021-09-16 16:29 UTC, tinnus-napbus commented
ok that's been merged so that particular problem is solved

2021-11-21 16:55 UTC, drbeefsupreme commented
Closing this by #1249

2021-11-21 16:55 UTC, closed without merging