docs: add software dist FAQ
urbit/urbit.org pull request #1167
Opened 2021-09-29 14:43 UTC by jamesacklin

Draft PR for the software dist FAQ.

Original gist from @eamsden:
https://gist.github.com/eamsden/359a2ed005502dcca8edf9213533772a

Base hashes forthcoming and marked as "TK."

2021-09-29 14:57 UTC, eamsden commented
When we have the OTA ready we should update this with base hashes in the table

2021-09-29 14:58 UTC, eamsden requested changes
using request changes to put a hold on this until we have base hashes

2021-09-29 14:58 UTC, eamsden commented on content/using/os/dist-faq.md
> +| Arvo/OS      | %base      | TK        |
This needs base hashes before publication

2021-09-29 14:59 UTC, eamsden commented
Also the /os/dist-faq path returns 404 on the preview deployment

2021-09-29 15:08 UTC, jamesacklin commented
Works on my machine(tm): https://urbit-org-k53c3g9ki-urbit.vercel.app/using/os/dist-faq

2021-09-29 16:37 UTC, eamsden commented
> Works on my machine(tm): https://urbit-org-k53c3g9ki-urbit.vercel.app/using/os/dist-faq

yeah sorry was a pebkac

2021-09-30 02:47 UTC, eamsden approved these changes
hashes are now in place

2021-09-30 02:48 UTC, merged