Some graph store cleanup (part 1)
urbit/urbit.org pull request #1228
Opened 2021-10-27 01:37 UTC by ynx0

Opening this early for visiblity.

**TODO**

- [x] combine old graph store reference doc
- [x] update scrys
- [x] update pokes
- [x] add input and output types for scries
- [x] explain agent state briefly, link to data structure overview for more info
- [x] update data structure overview (graph-update-3: new `%app` case in reference)

To be done in part 2
- [ ] hooks
	- [ ] gut out any references to hooks
	- [ ] move to separate specific page just talking about hooks
	- [ ] replace all current references to dedicated page
- [ ] refresh permalinks
- [ ] naming: graph-store vs. `%graph-store` vs. Graph Store

2021-11-19 02:57 UTC, tinnus-napbus commented
yo I may have ticked or unticked a task accidentally sorry. I think I've put it back how it was

2021-12-04 13:25 UTC, ynx0 commented
@tinnus-napbus this is ready for review btw

2021-12-08 08:03 UTC, tinnus-napbus requested changes
Looks good, just fixed the link and also slight structure change to pokes so it's more readable. Also - a few of the sentences don't have periods at the end and/or don't start with capital letters, particularly when they're bullet-points - these should be fixed

2021-12-08 08:03 UTC, tinnus-napbus commented on content/docs/userspace/graph-store/graph-store-reference.md
> +For more information on these types, please take a look at the (data structure overview)[/docs/userspace/graph-store/data-structure-overview.md].
```suggestion
For more information on these types, please take a look at the [data structure overview](/docs/userspace/graph-store/data-structure-overview).
```

2021-12-08 08:03 UTC, tinnus-napbus commented on content/docs/userspace/graph-store/graph-store-reference.md
> +  `[%run-updates =resource =update-log]`
```suggestion
Graph Store can be poked with a `graph-update`, which can:

### Add and remove a graph

- `[%add-graph =resource =graph mark=(unit mark) overwrite=?]`

- `[%remove-graph =resource]`

### Add and remove a node

- `[%add-nodes =resource nodes=(map index node)]`

- `[%remove-posts =resource indices=(set index)]`

### Add and remove signatures

- `[%add-signatures =uid =signatures]`

- `[%remove-signatures =uid =signatures]`

### Add and remove tags

- `[%add-tag =term =uid]`

- `[%remove-tag =term =uid]`

### Archive and unarchive a graph

- `[%archive-graph =resource]`

- `[%unarchive-graph =resource]`

### Manually process an update log on a resource

- `[%run-updates =resource =update-log]`
```

2021-12-09 08:51 UTC, tinnus-napbus approved these changes

2021-12-09 08:52 UTC, merged