change home->base throughout docs
urbit/urbit.org pull request #1312
Opened 2022-01-17 12:34 UTC by tinnus-napbus

this updates all reference to the home desk except for the ford explanation and some paths printed in the jetting doc

regarding #1304

2022-01-18 15:53 UTC, drbeefsupreme requested changes

2022-01-18 15:53 UTC, drbeefsupreme commented on content/docs/hoon/guides/cli-tutorial.md
> +reference `card:shoe` because of `/+ shoe` at the beginning of the app.
```suggestion
reference `card:shoe` because of `/+  shoe` at the beginning of the app.
```

2022-01-18 15:53 UTC, drbeefsupreme approved these changes

2022-01-18 15:59 UTC, drbeefsupreme commented
I do think the Ford post should be altered as I wrote in #1304 but I'm not adamant enough about it to stop this from being merged.

2022-01-18 15:59 UTC, drbeefsupreme commented
Not sure why the build is failing though.

2022-01-19 02:36 UTC, tinnus-napbus commented
hmm I merged master and now it builds, dunno what's up with that. Also sorry about of the weird whitespace changes, it seems markdown-mode does it automatically. I would note, though, that whitespace is collapsed for inline code, so the space you've re-added will not be displayed

2022-01-19 02:36 UTC, merged