Create community-meetups.md
urbit/urbit.org pull request #1662
Opened 2022-07-22 22:16 UTC by thelifeandtimes

@mikeosborne you game to be the champion on these? or should we make it @thomasurbit <<< is that your github ~dalweb-donfun?

2022-07-24 10:08 UTC, thomasurbit commented
Yes this is me. If possible I would like to champion it.

2022-07-25 17:27 UTC, thelifeandtimes commented
> Yes this is me. If possible I would like to champion it.

ok, made you the champion on these.

2022-07-25 18:44 UTC, mikeosborne commented on content/grants/community-meetups.md
> +- You must host a total of six meetups, with a target once a month.
```suggestion
- You must host a total of six meetups, with a targeted cadence of once a month.
```

2022-07-25 18:45 UTC, mikeosborne commented on content/grants/community-meetups.md
> +- Creation and admin of an Urbit group for your locality to which all meetup attendees will be invited, or a fully public group. This group should be actively maintained with info about upcoming even
```suggestion
- Creation and admin of an Urbit group for your locality to which all meetup attendees will be invited or a fully public group. This group should be actively maintained with info about upcoming events, copies of past presentation materials, or other related meetup content.
```

2022-07-25 19:02 UTC, mikeosborne commented on content/grants/community-meetups.md
> +- While the specific requirements of the meetup bounty listed below can be summarized as, "run a regular meetup," the overarching goal is to onboard people to Urbit. To judge a meetup as truly succes
```suggestion
- While the specific requirements of the meetup bounty listed below can be summarized as, "run a regular meetup," the overarching goal is to build a local community and onboard people to Urbit. Successful meetups will be judged by metrics like how many proposals have attendees submitted and completed and how many people have been onboarded who go on to positively contribute to the culture, technology, or creativity of the network. This does not mean that every meetup is expected to be full of developers or that a meetup that does not have a huge and ever-growing attendee list would be considered a failure. What it does mean is that meetup organizers and participants should become true champions for Urbit who can't help but share with everyone around them how Urbit can offer solutions to many of the pains of modern networked computing.
```

2022-07-25 19:04 UTC, mikeosborne requested changes
I would prefer the term Community Organizer rather than Meetup Organizer. What do you think?

2022-07-25 19:33 UTC, thelifeandtimes commented
> I would prefer the term Community Organizer rather than Meetup Organizer. What do you think?

Works for me.

2022-07-25 19:53 UTC, mikeosborne commented on content/grants/community-meetups.md
> +- While the specific requirements of the meetup bounty listed below can be summarized as "run a regular meetup", the overarching goal is to build a local community and onboard people to Urbit. Succes
```suggestion
- While the specific requirements of the meetup bounty listed below can be summarized as "run a regular meetup", the overarching goal is to build a local community and onboard people to Urbit. Successful meetups will be judged by metrics like how many proposals have attendees submitted and completed and how many people have been onboarded who go on to positively contribute to the culture, technology, or creativity of the network. This does not mean that every meetup is expected to be full of developers or that a meetup that does not have a huge and ever-growing attendee list would be considered a failure. What it does mean is that community organizers and participants should become true champions for Urbit who can't help but share with everyone around them how Urbit can offer solutions to many of the pains of modern networked computing.
```

2022-07-25 20:02 UTC, thomasurbit commented
Yes I like the new phrasing, makes the role in the community more long-term oriented and broader.

2022-07-26 02:01 UTC, thelifeandtimes commented
@mikeosborne can you merge this today?

2022-07-26 18:04 UTC, mikeosborne approved these changes

2022-07-26 18:04 UTC, merged