getting involved with urbit
urbit/urbit.org pull request #1806
Opened 2022-09-23 04:10 UTC by gordoncc

link list of @thelifeandtimes and @nealdavis's talk

2022-09-23 04:24 UTC, gordoncc commented
New page at /getinvolved

2022-09-23 11:55 UTC, sigilante commented on pages/getinvolved.js
> +	         • <Link href="https://developers.urbit.org/courses">Take a course on hoon</Link>
Capitalize Hoon

2022-09-23 11:56 UTC, sigilante requested changes
Comments.

2022-09-23 11:57 UTC, sigilante commented on pages/getinvolved.js
> +	         • <Link href="https://developers.urbit.org/courses">Take a course on hoon</Link>
Maybe "Take a course on Hoon or building apps."

2022-09-24 13:35 UTC, sigilante approved these changes

2022-09-24 14:50 UTC, thelifeandtimes commented
lgtm, merging.

2022-09-24 14:50 UTC, merged