App updates
urbit/urbit.org pull request #2018
Opened 2023-02-15 00:55 UTC by gordoncc

- adding talk and groups to tlon, fixing talk/groups shortcode
- adding scooore and %page to apps

2023-02-15 16:27 UTC, thomasurbit commented
~zod is probably not a good ship to hold them under as that will be transferred to the UF soon. I would just add their distribution ship as I don't expect it to change: ~marnec-dozzod-marzod

2023-02-15 17:41 UTC, gordoncc commented
> ~zod is probably not a good ship to hold them under as that will be transferred to the UF soon. I would just add their distribution ship as I don't expect it to change: ~marnec-dozzod-marzod

Updated blog to not have ~zod as the developer.  As for Tlon, for some reason entering Tlon as the developer  doesn't create a link to the Tlon page.  Entering in "~zod" does.  No idea why, I'd have to dig into the code.  It's just an internal thing and doesn't effect any data displayed, so I'll add that as a to do and address in a separate PR later.

2023-02-15 17:42 UTC, gordoncc commented
Oh, and isn't the distribution ship for Tlon apps "~sogryp-dister-dozzod-dozzod"?  Has that changed recently?

2023-02-15 18:28 UTC, jalehman commented
> ~zod is probably not a good ship to hold them under as that will be transferred to the UF soon. I would just add their distribution ship as I don't expect it to change: ~marnec-dozzod-marzod

Definitely not ~marnec. That's a prerelease distribution ship. Ask Tlon -- @jamesacklin or @zalberico

2023-02-15 18:31 UTC, jamesacklin commented
~sogryp-dister-dozzod-dozzod for Talk and Groups
~mister-dister-dozzod-dozzod for Landscape (%garden)

2023-02-15 18:32 UTC, zalberico commented
See: https://martiancomputing.substack.com/p/urbit-troubleshooting-basics
```
%garden   | source ship: ~mister-dister-dozzod-dozzod
%webterm  | source ship: ~mister-dister-dozzod-dozzod
%landscape| source ship: ~lander-dister-dozzod-dozzod
%groups   | source ship: ~sogryp-dister-dozzod-dozzod
%talk     | source ship: ~sogryp-dister-dozzod-dozzod
```

2023-02-15 18:46 UTC, gordoncc commented
Thanks guys, I think we've got the ships all in order.

2023-02-15 19:28 UTC, jalehman requested changes

2023-02-15 19:28 UTC, jalehman commented on content/applications/~sogryp-dister-dozzod-dozzod/groups.md
> +developer = "~zod"
Update per Zach's & James' comments.

2023-02-15 19:28 UTC, jalehman commented on content/applications/~sogryp-dister-dozzod-dozzod/talk.md
> +developer = "~zod"
Update per Zach's & James' comments.

2023-02-15 20:21 UTC, jalehman requested changes
Why is the developer still listed as zod? I see that the distribution shops are correct, so my original comment was misplaced, but zod is not the developer -- Tlon is.

2023-02-15 21:04 UTC, gordoncc commented
> Why is the developer still listed as zod? I see that the distribution shops are correct, so my original comment was misplaced, but zod is not the developer -- Tlon is.

Either ~zod or Tlon should work fine.  The original Tlon apps were listed under ~zod.  I'm not sure how the matching code works, but I'm guessing ~zod matches enough of the Tlon moons name.  Changed it to "Tlon".

2023-02-16 12:20 UTC, jalehman approved these changes

2023-02-16 13:17 UTC, merged