Add anchor links
urbit/urbit.org pull request #551
Opened 2021-01-20 16:37 UTC by ynx0

This is a draft pr for adding anchor links as discussed in #285.  
I have created the `anchor-link.html` template and added styling for it in `_main.scss`. 
Then, one can add `insert_anchor_links = "right"` to any section's front matter and expect it to work ([docs](https://www.getzola.org/documentation/content/linking/#anchor-insertion)) I tried it out with `urbit.org/contents/docs` and it seemed to work nicely, but I didn't know where it would actually be appropriate to put it so I haven't made that change yet. Also, since it is a submodule I don't know exactly how I would update that alongside the urbit.org repo. 
Since I am new to contributing I don't exactly know the conventions for the repo so please let me know if you need changes made before merging.

2021-01-20 16:50 UTC, matildepark commented
I would put both the option to set this in front matter; and make it on by default in some templates. Then the docs templates can get the anchors without needing to update every page in the Urbit/docs repo.

2021-01-20 18:44 UTC, ynx0 commented
Hmm, I know what you mean but I don't know how to make it enabled by default on all children article on docs. From the zola documentation, it says that the "`insert_anchor_links` property is set at the section level". We'd want to avoid manually setting this in every header like you said but even after looking for a bit it's not obvious to me how we could accomplish that.

2021-01-20 18:45 UTC, matildepark commented
Then we'll want a related PR on the section templates on urbit/docs:

https://github.com/urbit/docs/blob/master/_index.md etc etc.

2021-01-22 01:38 UTC, ynx0 commented
Relevant PR filed at https://github.com/urbit/docs/pull/1014. I think it makes sense for this one to be merged first.

2021-02-16 19:09 UTC, matildepark requested changes
Creates some general hijinks I had to fix by forcibly updating the submodule. Could you just rebase this and remove the submodule changes entirely? It's not really relevant to the PR.

2021-02-16 21:49 UTC, ynx0 commented
Ok, wow figuring out that I needed to force push after rebasing took forever but I think that should make it work... Let me know if it still needs some prodding.

2021-02-16 21:51 UTC, matildepark approved these changes
lgtm

2021-03-17 21:47 UTC, merged