More copy improvements
urbit/urbit.org pull request #556
Opened 2021-01-28 20:46 UTC by jalehman

There are a few things rolled into this:

* FAQ: I've moved the **Objections to Urbit** header to the bottom and renamed it to **Miscellaneous**. Calling out "objections" is a good way to make an otherwise unaware person that such objections exist in the first place. There's no need for this.
* Breach Banner: We're nearly two months past this and it looks kind of scary. If anyone's opposed to that, I'll put it back.
* Install + Setup: I've renamed this link to **Join the Network**, re-captioned it with copy that doesn't mention the CLI, and moved it to the top of the list. This is our only real Call to Action, so it should be prominent.

2021-01-28 22:32 UTC, drbeefsupreme requested changes
I definitely agree with moving the objections further down the page and renaming to Miscellaneous.

I think the "Why are there not more planets" and "Why is it currently expensive to acquire a planet" (which actually has a typo - it says "is is" instead of "is it") should not be moved so far though - perhaps put them under the Urbid ID section.

Same for "Can I host my Urbit with someone else" - maybe under Urbit ID as well, but I'm less sure about that. We definitely want people to know hosting is available, and the FAQ is rather long.

2021-01-29 20:07 UTC, matildepark approved these changes

2021-02-01 19:42 UTC, galenwp approved these changes
works for me!

2021-02-02 19:59 UTC, jalehman commented
> Same for "Can I host my Urbit with someone else" - maybe under Urbit ID as well, but I'm less sure about that. We definitely want people to know hosting is available, and the FAQ is rather long.

Doesn't really seem like an Urbit ID related question. I think this question is adequately answered in other places, like the install guide, so I'm less concerned with this being front and center.

2021-02-02 20:00 UTC, merged