Added grants to website
urbit/urbit.org pull request #604
Opened 2021-04-22 15:45 UTC by tylershuster

For further review with @jalehman

2021-04-22 15:49 UTC, tylershuster commented
Not sure why the CI preview isn't working; anyway except for the `post_type`  view, this is pretty much in a reviewable state

2021-04-22 15:52 UTC, jalehman commented
<img width="712" alt="Screen Shot 2021-04-22 at 8 51 40 AM" src="https://user-images.githubusercontent.com/550978/115745123-fe563480-a347-11eb-9113-cdb3a118d8fa.png">

😂

2021-04-23 00:01 UTC, tylershuster commented
This also needs some mobile responsivity work

2021-05-19 14:51 UTC, jalehman reviewed
A few high-level things:

Let's make the url `urbit.org/grants` rather than `urbit.org/community/grants-and-bounties`. We can still have it be accessible via the community page in terms of content, but top-level routes are better for SEO, and shorter URLs are easier to work with.

Make sure to remove the `content/docs` commit.

2021-05-19 14:51 UTC, jalehman commented on content/community/grants-and-bounties/-smol-future-sustained-knowledge-sharing-and-marketing.md
> +
Why so much whitespace?

2021-05-19 14:51 UTC, jalehman commented on content/community/grants-and-bounties/thread-documentation.md
> +completed = false
```suggestion
completed = true
```

2021-05-19 14:51 UTC, jalehman commented on content/community/grants-and-bounties/bitcoin-full-node-provider-and-wallet.md
> +completed = false
```suggestion
completed = true
```

2021-05-19 14:51 UTC, jalehman commented on content/community/grants-and-bounties/bitcoin-key-derivation.md
> +completed = false
```suggestion
completed = true
```

2021-05-19 14:51 UTC, jalehman commented on content/community/grants-and-bounties/haskell-airlock-library.md
> +completed = false
```suggestion
completed = true
```

2021-05-19 14:51 UTC, jalehman commented on content/community/grants-and-bounties/staff-the-urbit-help-desk-1.md
> +completed = false
```suggestion
completed = true
```

2021-05-19 14:51 UTC, jalehman commented on content/community/grants-and-bounties/staff-the-urbit-help-desk-2.md
> +completed = false
```suggestion
completed = true
```

2021-05-19 14:51 UTC, jalehman commented on content/community/grants-and-bounties/staff-the-urbit-helpdesk-east.md
> +completed = false
```suggestion
completed = true
```

2021-05-19 14:51 UTC, jalehman commented on content/community/grants-and-bounties/staff-the-urbit-helpdesk-west.md
> +completed = false
```suggestion
completed = true
```

2021-05-19 14:51 UTC, jalehman commented on content/community/grants-and-bounties/the-complete-guide-to-gall-and-landscape.md
> +reward = 2
```suggestion
reward = 4
```

2021-05-19 14:51 UTC, jalehman commented on content/community/grants-and-bounties/the-complete-guide-to-gall-and-landscape.md
> +completed = false
```suggestion
completed = true
```

2021-05-19 14:51 UTC, jalehman commented on content/community/grants-and-bounties/typescript-airlock-library.md
> +completed = false
```suggestion
completed = true
```

2021-05-19 14:51 UTC, jalehman commented on content/community/grants-and-bounties/up-to-date-hoon-reference-card.md
> +completed = false
```suggestion
completed = true
```

2021-05-19 15:02 UTC, jalehman requested changes
A few more changes. I'll get real metrics and forms to you within the next couple of days.

2021-05-19 15:02 UTC, jalehman commented on templates/grants/list.html
> +  <p>Urbit is a community project. While anyone can contribute, we help focus development and reward exceptional contribution through our grants and bounties program.</p>
```suggestion
  <p>Urbit is a community project. While anyone can contribute, we help focus development and reward exceptional contribution through our grants program.</p>
```
A bounty is a type of grant.

2021-05-19 15:02 UTC, jalehman commented on templates/index.html
> +    <p><a href="web+urbitgraph://group/~bitbet-bolbel/urbit-community/graph/~darrux-landes/development" class="bb" target="_blank">Development channel on Urbit</a></p>
```suggestion
    <p><a href="web+urbitgraph://group/~bitbet-bolbel/urbit-community/graph/~darrux-landes/development" class="bb" target="_blank">Development channel on Landscape</a></p>
```

2021-05-19 15:02 UTC, jalehman commented on templates/index.html
> +  <h1 class="mb3">Grants and Development</h1>
```suggestion
  <h1 class="mb3">Grants Program</h1>
```

2021-05-19 15:02 UTC, jalehman commented on templates/grants/list.html
> +    <li class="mb2"><a class="b bb" href="/grant-type/proposal">Proposals</a> from community members</li>
Per a previous comment, can this URL be `https://urbit.org/grants/proposals`? Or does it have to be `grant-type` per the taxonomy definition?

2021-05-19 15:02 UTC, jalehman commented on templates/grants/list.html
> +    <li class="mb2"><a class="b bb" href="/grant-type/bounty">Bounties</a> for specific features</li>
This would become `/grants/bounties` per the above comment.

2021-05-19 15:02 UTC, jalehman commented on templates/grants/list.html
> +    <li class="mb2"><a class="b bb" href="/community/apprenticeships">Apprenticeships</a> undertaken with a mentor</li>
and this would become `/grants/apprenticeships`

2021-05-19 15:02 UTC, jalehman commented on templates/grants/list.html
> +    <li class="mb2"><a class="b bb" href="/post-type/gift">Gifts</a> given post facto for exceptional contributions</li>
...and this would become `/grants/gifts`

2021-05-19 15:02 UTC, jalehman commented on templates/grants/list.html
> +  <p>This is a partial list, check <a href="https://grants.urbit.org" target="_blank" class="bb">grants.urbit.org</a> to see more and apply for a grant or propose your own.</p>
Remove this, since this will now be a complete list.

2021-05-19 15:05 UTC, jalehman commented
Here's the [proposal submission](https://airtable.com/shrCi54rEDxgSZr3z) form. Still working on the Bounty Work Request form and the Request Payment form.

2021-05-20 23:18 UTC, jalehman commented
Here's the [invoice submission form](https://airtable.com/shrXXCs1uaxtNSBcg).

2021-05-26 01:01 UTC, mikeosborne commented
The "Apply for this grant" links point to the grants website. We are replacing this with airtable forms. There will be a separate URL for each worker request. Can the template be updated to use these?

2021-05-27 23:59 UTC, mikeosborne commented
I have a proposal template that I refer to in the proposal submission static page. Where should it live?

2021-05-28 13:39 UTC, jalehman commented
@mikeosborne This got merged through a separate branch, so please submit your latest commit as a separate PR against master. Thanks!

2021-05-28 13:39 UTC, closed without merging