20210601 grants update
urbit/urbit.org pull request #636
Opened 2021-06-01 19:41 UTC by mikeosborne

Added 3rd party software distribution apprenticeship already completed by Raghu

2021-06-01 20:44 UTC, mikeosborne commented
@jalehman - the vane documentation bounty has a couple of missing links marked with "TODO"

2021-06-02 16:28 UTC, jalehman requested changes
Just a few changes about the calendar UI.

2021-06-02 16:28 UTC, jalehman commented on content/grants/bounty-calendar-ui.md
> +grant_type = ["bounties"]
This is a proposal, not a bounty.

2021-06-02 16:28 UTC, jalehman commented on content/grants/bounty-calendar-ui.md
> +reward = 5
This should be 3, not 5

2021-06-02 16:28 UTC, jalehman commented on content/grants/bounty-calendar-ui.md
> +link = "https://airtable.com/shr4qt9t9kz7RaOIa?prefill_Grant+ID=B0014&prefill_Grant+Name=ucal%20Google%20and%20Outlook%20Integration"
This isn't necessary

2021-06-02 16:28 UTC, jalehman commented on content/grants/bounty-calendar-ui.md
> +id = "B0014"
I think the ID maps to something @tylershuster implemented for the old grants site. Might want to double check the template to make sure this doesn't create any weird links.

2021-06-02 16:28 UTC, jalehman commented on content/grants/bounty-calendar-ui.md
> +Completion of all 9 features: 5 stars
See above about reward.

2021-06-03 16:25 UTC, jalehman commented
I see two calendar UI grants now: ![image](https://user-images.githubusercontent.com/550978/120679055-9a964f80-c44d-11eb-8a34-0b9ec92ae1fb.png)

2021-06-03 16:26 UTC, jalehman commented
And they both still seem to be listed under bounties for some reason.

2021-06-09 02:26 UTC, mikeosborne commented
commits folded into #639

2021-06-09 02:26 UTC, closed without merging