Matt/bitcoin instructions
urbit/urbit.org pull request #646
Opened 2021-06-15 20:19 UTC by tirwyd-sarmes

A basic set of instructions for %btc-wallet pending a docs section for urbit apps.

2021-06-16 20:46 UTC, jalehman requested changes
A few small changes, and then looks good!

2021-06-16 20:46 UTC, jalehman commented on content/Bitcoin-wallet.md
> +Run `|start %btc-wallet` in the dojo. In the first row of tiles on Landscape you should now see an orange bitcoin tile. Clicking on it will prompt a two-step process:
Does the page need to be refreshed?

2021-06-16 20:46 UTC, jalehman commented on content/Bitcoin-wallet.md
> +1. Enter a provider who is connected to a full-node (such as `~matwet`). This provider will maintain a synced Bitcoin ledger and process your transactions.
And also index your addresses for balance determination.

2021-06-16 20:46 UTC, jalehman commented on content/Bitcoin-wallet.md
> +2. The next step is to provide an xPub key. An xPub key will allow %btc-wallet to automatically generate new public addresses when bitcoin is sent to your ship. To provide an xPub you can either subm
```suggestion
2. The next step is to provide an extended public key (or xpub). Providing your xpub allows the Bitcoin Wallet to automatically generate new public addresses (called *child public keys*—you can learn more about this [here](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)) when bitcoin is sent to your ship. To provide an xpub you can either enter your master ticket (which can be downloaded from [Bridge](https://bridge.urbit.org)), or directly import your xpub (such as from a hardware wallet like [Ledger](https://support.ledger.com/hc/en-us/articles/360011069619-Extended-public-key) or [Trezor](https://wiki.trezor.io/User_manual:Displaying_account_public_key_(XPUB))).
```

2021-06-16 20:46 UTC, jalehman commented on content/Bitcoin-wallet.md
> +Using the landscape tile you can now view your balance and send bitcoin. All that is required to send bitcoin is the recipient’s ship name.
```suggestion
Clicking on the Landscape tile will take you to the Bitcoin Wallet application, where you can view your balance and send bitcoin. All that you'll need to do is enter the recipient's Urbit ID (if they have configured the wallet using the above steps) or a Bitcoin address.
```

2021-06-16 20:46 UTC, jalehman commented on content/Bitcoin-wallet.md
> +If you are interested in [being a provider](https://subject.network/posts/btc-wallet-config/#connecting-a-provider-to-a-full-node) or [running a bitcoin full node](https://subject.network/posts/pi-fu
```suggestion
If you are interested in [being a provider](https://subject.network/posts/btc-wallet-config/#connecting-a-provider-to-a-full-node) or [running a bitcoin full node](https://subject.network/posts/pi-fullnode-urbit/#bitcoind) on the Urbit network please check out `~sitful-hatred`’s excellent tutorials.
```

2021-06-17 16:44 UTC, jalehman commented on content/Bitcoin-wallet.md
> +1. Enter a provider who is connected to a full-node (such as `~matwet`). This provider will maintain a synced Bitcoin ledger and process your transactions.
```suggestion
1. Enter a provider who is connected to a full-node (such as `~matwet`). The provider will maintain a synced Bitcoin ledger, index your public addresses to determine your balance, and process your transactions.
```

2021-06-17 16:46 UTC, tirwyd-sarmes commented on content/Bitcoin-wallet.md
> +Run `|start %btc-wallet` in the dojo. In the first row of tiles on Landscape you should now see an orange bitcoin tile. Clicking on it will prompt a two-step process:
Yes! Good catch.

2021-06-17 16:49 UTC, merged