Tm/runtime apprenticeships
urbit/urbit.org pull request #664
Opened 2021-06-24 15:06 UTC by timlucmiptev

@jalehman @mikeosborne

2021-06-24 20:44 UTC, jalehman commented
Why are apprenticeships being deleted @timlucmiptev ? It looks like there are contributors that have signed up to work on these ones specifically.

2021-06-25 05:53 UTC, timlucmiptev commented
Ah, you're right, we shouldn't delete. I wanted to sort of mark them as
closed since I want people to do others.

Чт, 24 июня 2021 г. в 23:44, Josh Lehman ***@***.***>:

> Why are apprenticeships being deleted @timlucmiptev
> <https://github.com/timlucmiptev> ? It looks like there are contributors
> that have signed up to work on these ones specifically.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/urbit.org/pull/664#issuecomment-867939258>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APQFPHPKT3OZWA2XVFUAR43TUOKLFANCNFSM47ICSESA>
> .
>

2021-06-29 12:19 UTC, timlucmiptev commented
ok, undeleted the ones I don't want available and marked them `[Closed]`.

@mikeosborne Can you look at the `ra-*` runtime ones and see what to insert in the `TODO` parts?

2021-06-29 14:30 UTC, jalehman requested changes

2021-06-29 14:30 UTC, jalehman commented on content/grants/apprenticeships/ua-heads-up-poker.md
> +title = "[Closed] Userspace Apprenticeship: Heads-Up Poker"
No need to write in `[Closed]` to the title—just set the `assignee` property to the `@p` of the person(s) that are working on it and it'll no longer be claimable.

2021-06-29 14:31 UTC, jalehman commented
Also, this doesn't build due to errors in the page topmatter. Please run locally to ensure that everything builds (see README for instructions).

2021-06-30 13:57 UTC, timlucmiptev commented
Should be good now -- @mikeosborne could you add work request links?

2021-07-01 13:48 UTC, jalehman commented
I'll add the links in a follow-up PR.

2021-07-01 13:48 UTC, merged