Mike login with urbit proposal
urbit/urbit.org pull request #667
Opened 2021-06-25 22:02 UTC by mikeosborne

2021-06-25 22:07 UTC, mikeosborne commented
This builds fine on my local repo, but fails here due to broken links in the docs. I'm unsure how to proceed.

2021-06-28 18:58 UTC, drbeefsupreme requested changes

2021-06-28 18:58 UTC, drbeefsupreme commented on content/blog/gifts-q1-2021.md
> +Twice a year we distribute address space to those that have made valuable contributions to Urbit. Pervious the rational and our thinking about the role of gifts can be seen in our previous gift annou
Really just fixing the typo but the sentence seemed awkward anyways so here's a suggested revision.
```suggestion
Twice a year we distribute address space to those that have made valuable contributions to Urbit. We've shared our rationale and thinking about the role of gifts in our previous gift announcements [here](https://urbit.org/blog/urbit-grants-and-mid-2019-gifts/) and [here](https://urbit.org/blog/gifts-q3-2020/).

Without further ado, here are the 2021 Q1 gift recipients (all to receive 1 star):
 ```

2021-06-28 20:31 UTC, stan914 commented on content/blog/gifts-q1-2021.md
> +~litmus-ritten	cultural acheivement
typo here - should be "achievement"

2021-06-29 23:29 UTC, mikeosborne commented
Closing because I mucked up commits. Dividing commits into separate PRs.

2021-06-29 23:29 UTC, closed without merging